<?php

namespace Database\Seeders;

use App\Models\Lesson;
use App\Models\Word;
use Illuminate\Database\Seeder;

class ChineseVocabSeeder extends Seeder
{
    public function run(): void
    {
        $lessons = [
            [
                'title' => 'Personas y roles',
                'slug' => 'personas-roles',
                'description' => 'Cómo llamar a las personas: señor, señora, estudiante, ellos...',
                'hsk_level' => 1,
                'order' => 1,
                'emoji' => '👤',
                'words' => [
                    [
                        'character' => '先生',
                        'pinyin' => 'xiān shēng',
                        'translation' => 'Señor / Esposo',
                        'type' => 'noun',
                        'emoji' => '👔',
                        'example_sentence' => '这位先生是我丈夫。',
                        'example_pinyin' => 'Zhè wèi xiānshēng shì wǒ zhàngfū.',
                        'example_translation' => 'Este señor es mi esposo.',
                    ],
                    [
                        'character' => '太太',
                        'pinyin' => 'tài tài',
                        'translation' => 'Señora / Esposa',
                        'type' => 'noun',
                        'emoji' => '👗',
                        'example_sentence' => '这位是王太太。',
                        'example_pinyin' => 'Zhè wèi shì Wáng tàitai.',
                        'example_translation' => 'Esta es la señora Wang.',
                    ],
                    [
                        'character' => '学生',
                        'pinyin' => 'xué shēng',
                        'translation' => 'Estudiante',
                        'type' => 'noun',
                        'emoji' => '🎒',
                        'example_sentence' => '我是学生，我在大学念书。',
                        'example_pinyin' => 'Wǒ shì xuéshēng, wǒ zài dàxué niànshū.',
                        'example_translation' => 'Soy estudiante, estudio en la universidad.',
                    ],
                    [
                        'character' => '他们 / 她们',
                        'pinyin' => 'tā men / tā men',
                        'translation' => 'Ellos / Ellas',
                        'type' => 'pronoun',
                        'emoji' => '👥',
                        'example_sentence' => '他们都是我的朋友。',
                        'example_pinyin' => 'Tāmen dōu shì wǒ de péngyǒu.',
                        'example_translation' => 'Todos ellos son mis amigos.',
                    ],
                    [
                        'character' => '同',
                        'pinyin' => 'tóng',
                        'translation' => 'Mismo / Juntos (ej: 同事 compañero de trabajo, 同学 compañero de clase)',
                        'type' => 'adjective',
                        'emoji' => '🤝',
                        'example_sentence' => '我们是同学。',
                        'example_pinyin' => 'Wǒmen shì tóngxué.',
                        'example_translation' => 'Somos compañeros de clase.',
                    ],
                ],
            ],
            [
                'title' => 'Familia',
                'slug' => 'familia',
                'description' => 'Habla de tu familia: papá, mamá, hijos, esposo/a...',
                'hsk_level' => 1,
                'order' => 2,
                'emoji' => '👨‍👩‍👧‍👦',
                'words' => [
                    [
                        'character' => '女儿',
                        'pinyin' => 'nǚ ér',
                        'translation' => 'Hija',
                        'type' => 'noun',
                        'emoji' => '👧',
                        'example_sentence' => '我有一个女儿。',
                        'example_pinyin' => 'Wǒ yǒu yī gè nǚ\'ér.',
                        'example_translation' => 'Tengo una hija.',
                    ],
                    [
                        'character' => '儿子',
                        'pinyin' => 'ér zi',
                        'translation' => 'Hijo',
                        'type' => 'noun',
                        'emoji' => '👦',
                        'example_sentence' => '我的儿子在小学念书。',
                        'example_pinyin' => 'Wǒ de érzi zài xiǎoxué niànshū.',
                        'example_translation' => 'Mi hijo estudia en la escuela primaria.',
                    ],
                    [
                        'character' => '孩子',
                        'pinyin' => 'hái zi',
                        'translation' => 'Niño / Hijo (general)',
                        'type' => 'noun',
                        'emoji' => '🧒',
                        'example_sentence' => '你有孩子吗？',
                        'example_pinyin' => 'Nǐ yǒu háizi ma?',
                        'example_translation' => '¿Tienes hijos?',
                    ],
                    [
                        'character' => '小孩',
                        'pinyin' => 'xiǎo hái',
                        'translation' => 'Niño / Niña pequeña',
                        'type' => 'noun',
                        'emoji' => '👶',
                        'example_sentence' => '这个小孩很可爱。',
                        'example_pinyin' => 'Zhège xiǎohái hěn kě\'ài.',
                        'example_translation' => 'Este niño es muy lindo.',
                    ],
                    [
                        'character' => '结婚了',
                        'pinyin' => 'jié hūn le',
                        'translation' => 'Casado/a / Se casó',
                        'type' => 'phrase',
                        'emoji' => '💍',
                        'example_sentence' => '我结婚了，我有一个先生。',
                        'example_pinyin' => 'Wǒ jiéhūn le, wǒ yǒu yī gè xiānshēng.',
                        'example_translation' => 'Estoy casada, tengo un esposo.',
                    ],
                ],
            ],
            [
                'title' => 'Trabajo y estudios',
                'slug' => 'trabajo-estudios',
                'description' => 'Vocabulario para hablar de tu trabajo y educación.',
                'hsk_level' => 1,
                'order' => 3,
                'emoji' => '💼',
                'words' => [
                    [
                        'character' => '工作',
                        'pinyin' => 'gōng zuò',
                        'translation' => 'Trabajo / Trabajar',
                        'type' => 'noun/verb',
                        'emoji' => '💼',
                        'example_sentence' => '我在公司工作。',
                        'example_pinyin' => 'Wǒ zài gōngsī gōngzuò.',
                        'example_translation' => 'Trabajo en una empresa.',
                    ],
                    [
                        'character' => '公司',
                        'pinyin' => 'gōng sī',
                        'translation' => 'Empresa / Compañía',
                        'type' => 'noun',
                        'emoji' => '🏢',
                        'example_sentence' => '他在哪里的公司工作？',
                        'example_pinyin' => 'Tā zài nǎlǐ de gōngsī gōngzuò?',
                        'example_translation' => '¿En qué empresa trabaja él?',
                    ],
                    [
                        'character' => '银行',
                        'pinyin' => 'yín háng',
                        'translation' => 'Banco',
                        'type' => 'noun',
                        'emoji' => '🏦',
                        'example_sentence' => '我先生在银行工作。',
                        'example_pinyin' => 'Wǒ xiānshēng zài yínháng gōngzuò.',
                        'example_translation' => 'Mi esposo trabaja en el banco.',
                    ],
                    [
                        'character' => '电脑',
                        'pinyin' => 'diàn nǎo',
                        'translation' => 'Computadora',
                        'type' => 'noun',
                        'emoji' => '💻',
                        'example_sentence' => '我每天用电脑工作。',
                        'example_pinyin' => 'Wǒ měitiān yòng diànnǎo gōngzuò.',
                        'example_translation' => 'Uso la computadora para trabajar todos los días.',
                    ],
                    [
                        'character' => '大学',
                        'pinyin' => 'dà xué',
                        'translation' => 'Universidad',
                        'type' => 'noun',
                        'emoji' => '🎓',
                        'example_sentence' => '我在大学念书。',
                        'example_pinyin' => 'Wǒ zài dàxué niànshū.',
                        'example_translation' => 'Estudio en la universidad.',
                    ],
                    [
                        'character' => '小学',
                        'pinyin' => 'xiǎo xué',
                        'translation' => 'Escuela primaria',
                        'type' => 'noun',
                        'emoji' => '🏫',
                        'example_sentence' => '我的孩子在小学。',
                        'example_pinyin' => 'Wǒ de háizi zài xiǎoxué.',
                        'example_translation' => 'Mi hijo está en la escuela primaria.',
                    ],
                    [
                        'character' => '念书',
                        'pinyin' => 'niàn shū',
                        'translation' => 'Estudiar / Leer (libros)',
                        'type' => 'verb',
                        'emoji' => '📚',
                        'example_sentence' => '我的女儿很喜欢念书。',
                        'example_pinyin' => 'Wǒ de nǚ\'ér hěn xǐhuān niànshū.',
                        'example_translation' => 'A mi hija le gusta mucho estudiar.',
                    ],
                    [
                        'character' => '毕业了',
                        'pinyin' => 'bì yè le',
                        'translation' => 'Se graduó / Terminó los estudios',
                        'type' => 'phrase',
                        'emoji' => '🎓',
                        'example_sentence' => '我已经大学毕业了。',
                        'example_pinyin' => 'Wǒ yǐjīng dàxué bì yè le.',
                        'example_translation' => 'Ya me gradué de la universidad.',
                    ],
                ],
            ],
            [
                'title' => 'Palabras esenciales',
                'slug' => 'palabras-esenciales',
                'description' => 'Partículas y palabras que usarás en casi todas las oraciones.',
                'hsk_level' => 1,
                'order' => 4,
                'emoji' => '🔤',
                'words' => [
                    [
                        'character' => '在',
                        'pinyin' => 'zài',
                        'translation' => 'En / Estar en',
                        'type' => 'preposition',
                        'emoji' => '📍',
                        'example_sentence' => '我在公司工作。',
                        'example_pinyin' => 'Wǒ zài gōngsī gōngzuò.',
                        'example_translation' => 'Trabajo en la empresa.',
                    ],
                    [
                        'character' => '都',
                        'pinyin' => 'dōu',
                        'translation' => 'Todo / Todos / Ambos',
                        'type' => 'adverb',
                        'emoji' => '✅',
                        'example_sentence' => '我们都是学生。',
                        'example_pinyin' => 'Wǒmen dōu shì xuéshēng.',
                        'example_translation' => 'Todos nosotros somos estudiantes.',
                    ],
                    [
                        'character' => '和',
                        'pinyin' => 'hé',
                        'translation' => 'Y / Con',
                        'type' => 'conjunction',
                        'emoji' => '➕',
                        'example_sentence' => '我和我先生都工作。',
                        'example_pinyin' => 'Wǒ hé wǒ xiānshēng dōu gōngzuò.',
                        'example_translation' => 'Mi esposo y yo trabajamos.',
                    ],
                    [
                        'character' => '很',
                        'pinyin' => 'hěn',
                        'translation' => 'Muy',
                        'type' => 'adverb',
                        'emoji' => '💯',
                        'example_sentence' => '我很高兴认识你。',
                        'example_pinyin' => 'Wǒ hěn gāoxìng rènshí nǐ.',
                        'example_translation' => 'Estoy muy contento/a de conocerte.',
                    ],
                    [
                        'character' => '不',
                        'pinyin' => 'bù',
                        'translation' => 'No (negación)',
                        'type' => 'adverb',
                        'emoji' => '❌',
                        'example_sentence' => '我不是学生，我工作。',
                        'example_pinyin' => 'Wǒ bù shì xuéshēng, wǒ gōngzuò.',
                        'example_translation' => 'No soy estudiante, yo trabajo.',
                    ],
                    [
                        'character' => '哪里',
                        'pinyin' => 'nǎ lǐ',
                        'translation' => '¿Dónde?',
                        'type' => 'pronoun',
                        'emoji' => '❓',
                        'example_sentence' => '你在哪里工作？',
                        'example_pinyin' => 'Nǐ zài nǎlǐ gōngzuò?',
                        'example_translation' => '¿Dónde trabajas?',
                    ],
                ],
            ],
            [
                'title' => 'Países e idiomas',
                'slug' => 'paises-idiomas',
                'description' => 'Nombres de países y cómo decir en qué idioma hablas.',
                'hsk_level' => 1,
                'order' => 5,
                'emoji' => '🌍',
                'words' => [
                    [
                        'character' => '中国',
                        'pinyin' => 'zhōng guó',
                        'translation' => 'China',
                        'type' => 'noun',
                        'emoji' => '🇨🇳',
                        'example_sentence' => '我在中国工作。',
                        'example_pinyin' => 'Wǒ zài zhōngguó gōngzuò.',
                        'example_translation' => 'Trabajo en China.',
                    ],
                    [
                        'character' => '法国',
                        'pinyin' => 'fǎ guó',
                        'translation' => 'Francia',
                        'type' => 'noun',
                        'emoji' => '🇫🇷',
                        'example_sentence' => '她是法国人。',
                        'example_pinyin' => 'Tā shì fǎguórén.',
                        'example_translation' => 'Ella es francesa.',
                    ],
                    [
                        'character' => '法文',
                        'pinyin' => 'fǎ wén',
                        'translation' => 'Idioma francés',
                        'type' => 'noun',
                        'emoji' => '🗣️',
                        'example_sentence' => '她会说法文和中文。',
                        'example_pinyin' => 'Tā huì shuō fǎwén hé zhōngwén.',
                        'example_translation' => 'Ella sabe hablar francés y chino.',
                    ],
                    [
                        'character' => '中文',
                        'pinyin' => 'zhōng wén',
                        'translation' => 'Idioma chino / Chino',
                        'type' => 'noun',
                        'emoji' => '🀄',
                        'example_sentence' => '我在学习中文。',
                        'example_pinyin' => 'Wǒ zài xuéxí zhōngwén.',
                        'example_translation' => 'Estoy aprendiendo chino.',
                    ],
                    [
                        'character' => '西班牙',
                        'pinyin' => 'xī bān yá',
                        'translation' => 'España',
                        'type' => 'noun',
                        'emoji' => '🇪🇸',
                        'example_sentence' => '我来自西班牙。',
                        'example_pinyin' => 'Wǒ láizì xībānyá.',
                        'example_translation' => 'Soy de España.',
                    ],
                    [
                        'character' => '西班牙文',
                        'pinyin' => 'xī bān yá wén',
                        'translation' => 'Idioma español',
                        'type' => 'noun',
                        'emoji' => '🗣️',
                        'example_sentence' => '我会说西班牙文。',
                        'example_pinyin' => 'Wǒ huì shuō xībānyáwén.',
                        'example_translation' => 'Sé hablar español.',
                    ],
                ],
            ],
            [
                'title' => 'Presentación personal',
                'slug' => 'presentacion-personal',
                'description' => 'Frases clave para presentarte: quién eres, dónde trabajas, tu familia.',
                'hsk_level' => 1,
                'order' => 6,
                'emoji' => '🙋',
                'words' => [
                    [
                        'character' => '我叫…',
                        'pinyin' => 'wǒ jiào…',
                        'translation' => 'Me llamo… / Mi nombre es…',
                        'type' => 'phrase',
                        'emoji' => '🏷️',
                        'example_sentence' => '我叫Gabriel，我在公司工作。',
                        'example_pinyin' => 'Wǒ jiào Gabriel, wǒ zài gōngsī gōngzuò.',
                        'example_translation' => 'Me llamo Gabriel, trabajo en una empresa.',
                    ],
                    [
                        'character' => '我是…',
                        'pinyin' => 'wǒ shì…',
                        'translation' => 'Soy… / Yo soy…',
                        'type' => 'phrase',
                        'emoji' => '👤',
                        'example_sentence' => '我是学生，我在大学念书。',
                        'example_pinyin' => 'Wǒ shì xuéshēng, wǒ zài dàxué niànshū.',
                        'example_translation' => 'Soy estudiante, estudio en la universidad.',
                    ],
                    [
                        'character' => '我在…工作',
                        'pinyin' => 'wǒ zài… gōng zuò',
                        'translation' => 'Trabajo en…',
                        'type' => 'phrase',
                        'emoji' => '🏢',
                        'example_sentence' => '我在银行工作。',
                        'example_pinyin' => 'Wǒ zài yínháng gōngzuò.',
                        'example_translation' => 'Trabajo en el banco.',
                    ],
                    [
                        'character' => '我有…',
                        'pinyin' => 'wǒ yǒu…',
                        'translation' => 'Tengo…',
                        'type' => 'phrase',
                        'emoji' => '✋',
                        'example_sentence' => '我有一个女儿和一个儿子。',
                        'example_pinyin' => 'Wǒ yǒu yī gè nǚ\'ér hé yī gè érzi.',
                        'example_translation' => 'Tengo una hija y un hijo.',
                    ],
                    [
                        'character' => '你在哪里工作？',
                        'pinyin' => 'nǐ zài nǎlǐ gōngzuò?',
                        'translation' => '¿Dónde trabajas?',
                        'type' => 'phrase',
                        'emoji' => '❓',
                        'example_sentence' => '你在哪里工作？我在银行工作。',
                        'example_pinyin' => 'Nǐ zài nǎlǐ gōngzuò? Wǒ zài yínháng gōngzuò.',
                        'example_translation' => '¿Dónde trabajas? Trabajo en el banco.',
                    ],
                    [
                        'character' => '你有孩子吗？',
                        'pinyin' => 'nǐ yǒu háizi ma?',
                        'translation' => '¿Tienes hijos?',
                        'type' => 'phrase',
                        'emoji' => '👨‍👩‍👧',
                        'example_sentence' => '你有孩子吗？有，我有两个孩子。',
                        'example_pinyin' => 'Nǐ yǒu háizi ma? Yǒu, wǒ yǒu liǎng gè háizi.',
                        'example_translation' => '¿Tienes hijos? Sí, tengo dos hijos.',
                    ],
                ],
            ],
        ];

        foreach ($lessons as $lessonData) {
            $words = $lessonData['words'];
            unset($lessonData['words']);

            $lesson = Lesson::create($lessonData);

            foreach ($words as $wordData) {
                $lesson->words()->create(array_merge($wordData, ['hsk_level' => $lesson->hsk_level]));
            }
        }
    }
}
